public class ContactTriggerHandler extends BaseTriggerHandler {
    public override void beforeInsert () {

    }

    public override void beforeUpdate () {
        
    }

    public override void beforeDelete () {
        
    }

    public override void afterInsert () {
        
    }

    public override void afterUpdate () {
        
    }

    public override void afterDelete () {
        
    }
}
